CREATE TABLE GROUP_M (
  GROUP_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  GROUP_NAME VARCHAR(20),
  STATUS_FLG TINYINT NOT NULL DEFAULT 0,
  REG_USER INT,
  REG_DATE DATETIME,
  UPD_USER INT,
  UPD_DATE DATETIME,
  PRIMARY KEY(GROUP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;