CREATE TABLE POSITION_MST (
  SEQ_NO SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  POSITION_ID VARCHAR(255) NOT NULL,
  POSITION_NAME VARCHAR(255) NOT NULL,
  POSITION_ALLOWANCE INT NOT NULL DEFAULT 0,
  STATUS_FLG TINYINT NOT NULL DEFAULT 0,
  REG_USER INT,
  REG_DATE DATETIME,
  UPD_USER INT,
  UPD_DATE DATETIME,
  PRIMARY KEY(SEQ_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
