CREATE TABLE USER_INFO (
  SEQ_NO SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ID VARCHAR(255) NOT NULL,
  NAME VARCHAR(20),
  PASSWORD VARCHAR(32),
  STATUS_FLG TINYINT NOT NULL DEFAULT 0,
  REG_USER INT,
  REG_DATE DATETIME,
  UPD_USER INT,
  UPD_DATE DATETIME,
  PRIMARY KEY(SEQ_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
